version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10
      - image: redis:6.2
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

      - run:
          name: Run tests
          command: |
            pytest
workflows:
  version: 2
  test:
    jobs:
      - build-and-test
