name: Test Workflow

on: [push]

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run a test command
        run: echo "🎉 Hello from act!"
